seo: 
  site_name: Tina's Amazing Blog
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-text_color: 'rgb(60,60,65)'
  medium-text_color: 'rgb(90,90,95)'
  light-text_color: '#f7f5f3'
  featured-text_color: '#839788'
  dark_color: '#2e2e2e'
  medium_color: '#585563'
  light_color: '#5A2C0F'
  v-light_color: 'rgb(230,230,230)'
  featured_color: '#839788'
  accent_color: 'rgb(167, 74, 74)'
